{% set name = "ocpsvg" %}
{% set version = "0.5.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ocpsvg-{{ version }}.tar.gz
  sha256: 5cd8dbec8bf590d373a82aaebeab241838185aab04ee2859f33b9d7956bbfba6
  patches:
    - 0001-Rename-dependencies-for-conda-forge-packages.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - ocp >=7.8.1,<7.9
    - python >={{ python_min }}
    - svgelements >=1.9.1,<2

test:
  source_files:
    - tests
  imports:
    - ocpsvg
  commands:
    - pytest -v tests/
  requires:
    - pytest
    - pip
    - python {{ python_min }}
    # The libgl dependency for the test section can likely be removed when
    # the following https://github.com/conda-forge/ocp-feedstock/pull/50
    # gets merged in the ocp feedstock
    # this helps avoid a yum dependency
    # either with the yum dependency or with this, the end user is assumed
    # to have X11 system dependencies installed
    # this helps the user avoid to have a direct dependency on libgl
    # from this package (it will be transitive from OCP once the PR gets merged)
    - libgl    # [linux]
    - libegl    # [linux]

about:
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/snoyer/ocpsvg
  summary: |
    Add SVG functionality (import and export) to higher level cadquery API
    - works at the OCP level
    - uses svgelements to import TopoDS_Wire and TopoDS_Face objects from an SVG document


extra:
  recipe-maintainers:
    - ndevenish
